### ISSUE TITLE
Congratulations on This Repo

### ISSUE THREAD

**Issue by trooks1017** [tjoudeh/AngularJSAuthentication#1]
I wanted to take a moment to thank you and congratulate you on this repository. I am still digesting it completely in my spare time (not a lot of that I am afraid). I especially liked the AngularJS module Run command to start up a service without a  inject into a controller. Since I am relatively new to AngularJS this really is a handy little tidbit of code. 
I am curious as to why you did not use a Service vs Factory concept here? It would appear that you want a Singleton pattern and the config would be more Angular I think with the service.
I realize that this is not really an issue, but I could not find a discussion link to add this comment. In any event, good luck with the project and nice starting point for those of us learning Microsoft.Owin.Security. I will continue following your twitter conversations.

**Comment by tjoudeh** [comment]
Hi,
You are right, if you are using localhost then you need to run both projects on the same time, they are two separate projects hosted locally on different ports.
All you need to do is to right click on project .API and choose "Debug" --- > "Start New Instance" and the same applies to the .Web project.
Hope this answers your questions.

Date: Fri, 25 Jul 2014 15:59:38 -0700

**Comment by tjoudeh** [comment]
Hi trooks1017,
Thanks for taking the time to read the posts and drop a comment.
Regarding the service in run event you are absolutely right, I wanted to used Singleton pattern here.
