### ISSUE TITLE
Question about new ResourceServer project

### ISSUE THREAD

**Issue by cb55555** [tjoudeh/AngularJSAuthentication#4]
I see that a new ResourceServer project has been added. However, I don't see that it's being called from the client application (AngularJSAuthentication.Web). Is it because it just hasn't been hooked up yet?

**Comment by tjoudeh** [comment]
Hi, you are right I didn't re-factor the code, but please read this blog post http://bit.ly/1mNb7ek to understand how to use it. I'll consider re-factoring it soon.
