### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by 2ooom** [tjoudeh/AngularJSAuthentication#5]
First thaks a lot for the articles and this repo, this really helped me to get with Owin.Security.OAuth2 which unfortuanately lacks decent examples or even comments on MSDN. So I really appeciate the job you did!

While reviewing the code I had came across a few questions:
1. [overriding TokenEndpoint](https://github.com/tjoudeh/AngularJSAuthentication/blob/master/AngularJSAuthentication.API/Providers/SimpleAuthorizationServerProvider.cs#L145-L153) seems to be unecessary could it be safely ommited?
2. Minor thing in [SimpleAuthorizationServerProvider.ValidateClientAuthentication](https://github.com/2ooom/AngularJSAuthentication/commit/9cd59fe5ca10d9e4da8403355f93210681a3caea#diff-45dfb650b9470ccba63ed13f18701d30R20) which made me to look inside Owin packages source code to understand why you first resolve `clientId` and than simply use `context.ClientId`? It seems like `context.ClientId` is available within whole method, but actually it would be populated indirectly only  in `TryGetFormCredentials`/`TryGetBasicCredentials` methods so [using local `clientId`](https://github.com/2ooom/AngularJSAuthentication/commit/9cd59fe5ca10d9e4da8403355f93210681a3caea) would be less confusing in terms of code readability IMHO.
3. Why would you want to persist AuthorizationTicket to database. I've noticed that there is a bit of workaround before creating new refresh tokens in [`CreateAsync`](https://github.com/tjoudeh/AngularJSAuthentication/blob/master/AngularJSAuthentication.API/Providers/SimpleRefreshTokenProvider.cs#L40-L41) when `Ticket.Properties.ExpiresUtc` and `Ticket.Properties.IssuedUtc` are set. Woudn't it be easier if we can factor out common logic for issuing tikets and reuse it in `GrantResourceOwnerCredentials` and `ReceiveAsync`?
4. In [`GrantResourceOwnerCredentials()`](https://github.com/tjoudeh/AngularJSAuthentication/blob/master/AngularJSAuthentication.API/Providers/SimpleAuthorizationServerProvider.cs#L103-L111) why are you storing `"as:client_Id"` and `"userName"`  inside ticket which would be sent through http with every single request to Resource Server and persisted into database? Why not use `IOwinContext.Set` instead the same way you were storing `""as:clientAllowedOrigin""`? And btw, why would you want to use `"as:"` prefix for most of your keys?

**Comment by ghost** [comment]
2ooom, can you do these changes, test, and do a Pull Request?

**Comment by tjoudeh** [comment]
@2ooom you are welcome. glad that this repo was useful in your implementation. Please find my answers below:
1 - You are correct, you can remove it if you do not want to include extra properties in /token response. In my case I needed the Username in the Angular App to display the username for the logged in user.
2 - context.ClientId will not be filled if you didn't call TryGetFormCredentials/TryGetBasicCredentials, I needed the context.ClientId to get filled because I'm using it in the GrantResourceOwnerCredentials method.
3 - Replied this in SO question
4 - You are correct, another way is to use context.set. "as" for Authorization Server, just to make sure key names are unique, you can omit this too.

**Comment by NikolajDL** [comment]
The properties included in the TokenEndpoint override, is invaluable for passing roles and permissions to the front-end.

**Comment by 2ooom** [comment]
Thank you for reply, guys. 
@tjoudeh 
**2** - was just about readability. See [this commit](https://github.com/2ooom/AngularJSAuthentication/commit/9cd59fe5ca10d9e4da8403355f93210681a3caea) to get the idea 
**3** - will do pull request later to be more specific
